name: workflow

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: extract-properties
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ steps.extract_branch.outputs.branch }}
          restore-keys: ${{ steps.extract_branch.outputs.branch }}
        if: github.ref == 'refs/heads/main'
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '17'
      - name: "Test the application"
        run: |
          mvn clean test